defaults:
  - _self_

task: qa
dataset: ['UGRIP-LM-Polygraph/medmcqa-reasoning', 'continuation']
text_column: question
label_column: answer
max_new_tokens: 256
# Do you need a space after? 
output_ignore_regex: "(?s).### Answer: "