- name: TrainMTopDivCalculator
  builder: lm_polygraph.defaults.stat_calculator_builders.default_TrainMTopDivCalculator
  cfg:
    heads_extraction_priority: cache
    cache_path: '${model_heads_cache}'
    max_heads: '${max_heads}'
    n_jobs: '${n_jobs}'
    train_data_path: '${train_dataset.train_data_path}'
    context_column: '${train_dataset.context}'
    question_column: '${train_dataset.question}'
    prompt_column: '${train_dataset.prompt}'
    response_column: '${train_dataset.generated_answer}'
    label_column: '${train_dataset.hallucination}'
    batch_size: '${batch_size}'
    subsample_train_dataset: '${train_dataset.subsample}'
    seed: '${seed}'
  stats: 
    - "topological_divergence_heads"
  dependencies: