additional_estimators: {}

dataset: ../triviaqa.csv
train_dataset: null
background_train_dataset: allenai/c4

model: databricks/dolly-v2-3b

use_density_based_ue: false
ignore_exceptions: true

subsample_background_train_dataset: 100
subsample_train_dataset: 10
subsample_eval_dataset: 10
batch_size: 2
seed:
    - 1
device: cpu

save_path: test.man
cache_path: .