defaults:
  - polygraph_eval_triviaqa_default_instruct
  - topk_processing_triviaqa
  - _self_

experiment_name: triviaqa_verb_2s_topk

topk: 4
dataset: [LM-Polygraph/triviaqa, verb_2s_topk]
description: "Provide your ${topk} best guesses for the following question. Give ONLY the guesses, no other words or explanation. For example:\n\nG1: <first most likely guess, as short as possible; not a complete sentence, just the guess!>\n...\nG${topk}: <${topk}-th most likely guess, as short as possible; not a complete sentence, just the guess!>"
few_shot_prompt: "Question: {question}\nG1: {answer}\n...\nG${topk}: <other guess>"
prompt: "Question: {question}\n"
max_new_tokens: 125

estimators:
  - name: Verbalized2S
    cfg:
      confidence_prompt: "Provide the probability that each of your guesses is correct. Give ONLY the probabilities, no other words or explanation.\n\nFor example:\n\nP1: <the probability between 0.0 and 1.0 that G1 is correct, without any extra commentary whatsoever; just the probability!>\n...\nP${topk}: <the probability between 0.0 and 1.0 that G${topk} is correct, without any extra commentary whatsoever; just the probability!>"
      confidence_regex: 'P1: (\d+\.\d+)'
      max_new_tokens: 50
      name_postfix: "_topk"

stat_calculators:
  - auto