defaults:
  - polygraph_eval_triviaqa_default_instruct
  - top1_processing_triviaqa
  - _self_

experiment_name: triviaqa_verb_2s_top1

dataset: [LM-Polygraph/triviaqa, verb_2s_top1]
description: "Provide your best guess for the following question. Give ONLY the guess, no other words or explanation.\n\nFor example:\n\nGuess: <most likely guess, as short as possible; not a complete sentence, just the guess!>"
few_shot_prompt: "Question: {question}\nGuess: {answer}"
prompt: "Question: {question}\n"
max_new_tokens: 30

estimators:
  - name: Verbalized2S
    cfg:
      confidence_prompt: "Provide the probability that your guess is correct. Give ONLY the probability, no other words or explanation.\n\nFor example:\n\nProbability: <the probability between 0.0 and 1.0 that your guess is correct, without any extra commentary whatsoever; just the probability!>"
      confidence_regex: 'Probability: (\d+\.\d+)'
      max_new_tokens: 10 
      name_postfix: "_top1"

stat_calculators:
  - auto