"""Public API, imported on demand to keep optional dependencies optional."""

from lm_polygraph._optional import lazy_exports

_EXPORTS = {
    "Estimator": (".estimator", "Estimator"),
    "ClaimConditionedProbabilityClaim": (
        ".claim.claim_conditioned_probability",
        "ClaimConditionedProbabilityClaim",
    ),
    "MaximumClaimProbability": (".claim.max_probability", "MaximumClaimProbability"),
    "PTrueClaim": (".claim.p_true", "PTrueClaim"),
    "AttentionScoreClaim": (".claim.attention_score", "AttentionScoreClaim"),
    "PerplexityClaim": (".claim.perplexity", "PerplexityClaim"),
    "MaxTokenEntropyClaim": (".claim.token_entropy", "MaxTokenEntropyClaim"),
    "PointwiseMutualInformationClaim": (
        ".claim.pointwise_mutual_information",
        "PointwiseMutualInformationClaim",
    ),
    "FocusClaim": (".claim.focus", "FocusClaim"),
    "FrequencyScoringClaim": (".claim.frequency_scoring", "FrequencyScoringClaim"),
    "TokenSARClaim": (".claim.token_sar", "TokenSARClaim"),
    "SelfCertaintyClaim": (".claim.self_certainty", "SelfCertaintyClaim"),
    "BoostedProbClaim": (".claim.boostedprob_score", "BoostedProbClaim"),
    "MaximumSequenceProbability": (".max_probability", "MaximumSequenceProbability"),
    "MaximumTokenProbability": (".max_probability", "MaximumTokenProbability"),
    "AttentionScore": (".attention_score", "AttentionScore"),
    "ClaimConditionedProbability": (
        ".claim_conditioned_probability",
        "ClaimConditionedProbability",
    ),
    "SelfCertainty": (".self_certainty", "SelfCertainty"),
    "MeanTokenEntropy": (".token_entropy", "MeanTokenEntropy"),
    "TokenEntropy": (".token_entropy", "TokenEntropy"),
    "MeanPointwiseMutualInformation": (
        ".pointwise_mutual_information",
        "MeanPointwiseMutualInformation",
    ),
    "PointwiseMutualInformation": (
        ".pointwise_mutual_information",
        "PointwiseMutualInformation",
    ),
    "MeanConditionalPointwiseMutualInformation": (
        ".conditional_pointwise_mutual_information",
        "MeanConditionalPointwiseMutualInformation",
    ),
    "ConditionalPointwiseMutualInformation": (
        ".conditional_pointwise_mutual_information",
        "ConditionalPointwiseMutualInformation",
    ),
    "PTrue": (".p_true", "PTrue"),
    "PTrueSampling": (".p_true_sampling", "PTrueSampling"),
    "MonteCarloSequenceEntropy": (
        ".monte_carlo_sequence_entropy",
        "MonteCarloSequenceEntropy",
    ),
    "MonteCarloNormalizedSequenceEntropy": (
        ".monte_carlo_normalized_sequence_entropy",
        "MonteCarloNormalizedSequenceEntropy",
    ),
    "LexicalSimilarity": (".lexical_similarity", "LexicalSimilarity"),
    "DegMat": (".deg_mat", "DegMat"),
    "Eccentricity": (".eccentricity", "Eccentricity"),
    "EigValLaplacian": (".eig_val_laplacian", "EigValLaplacian"),
    "NumSemSets": (".num_sem_sets", "NumSemSets"),
    "SemanticEntropy": (".semantic_entropy", "SemanticEntropy"),
    "SemanticEntropyToken": (".semantic_entropy_token", "SemanticEntropyToken"),
    "Perplexity": (".perplexity", "Perplexity"),
    "MahalanobisDistanceSeq": (".mahalanobis_distance", "MahalanobisDistanceSeq"),
    "RelativeMahalanobisDistanceSeq": (
        ".relative_mahalanobis_distance",
        "RelativeMahalanobisDistanceSeq",
    ),
    "RDESeq": (".rde", "RDESeq"),
    "PPLMDSeq": (".ppl_md", "PPLMDSeq"),
    "BoostedProbSequence": (".boostedprob_score", "BoostedProbSequence"),
    "EPTtu": (".ensemble_token_measures", "EPTtu"),
    "EPTdu": (".ensemble_token_measures", "EPTdu"),
    "EPTmi": (".ensemble_token_measures", "EPTmi"),
    "EPTrmi": (".ensemble_token_measures", "EPTrmi"),
    "EPTepkl": (".ensemble_token_measures", "EPTepkl"),
    "EPTent5": (".ensemble_token_measures", "EPTent5"),
    "EPTent10": (".ensemble_token_measures", "EPTent10"),
    "EPTent15": (".ensemble_token_measures", "EPTent15"),
    "PETtu": (".ensemble_token_measures", "PETtu"),
    "PETdu": (".ensemble_token_measures", "PETdu"),
    "PETmi": (".ensemble_token_measures", "PETmi"),
    "PETrmi": (".ensemble_token_measures", "PETrmi"),
    "PETepkl": (".ensemble_token_measures", "PETepkl"),
    "PETent5": (".ensemble_token_measures", "PETent5"),
    "PETent10": (".ensemble_token_measures", "PETent10"),
    "PETent15": (".ensemble_token_measures", "PETent15"),
    "EPStu": (".ensemble_sequence_measures", "EPStu"),
    "EPSrmi": (".ensemble_sequence_measures", "EPSrmi"),
    "EPSrmiabs": (".ensemble_sequence_measures", "EPSrmiabs"),
    "PEStu": (".ensemble_sequence_measures", "PEStu"),
    "PESrmi": (".ensemble_sequence_measures", "PESrmi"),
    "PESrmiabs": (".ensemble_sequence_measures", "PESrmiabs"),
    "TokenSAR": (".token_sar", "TokenSAR"),
    "SentenceSAR": (".sentence_sar", "SentenceSAR"),
    "SAR": (".sar", "SAR"),
    "RenyiNeg": (".renyi_neg", "RenyiNeg"),
    "FisherRao": (".fisher_rao", "FisherRao"),
    "Verbalized1S": (".verbalized_1s", "Verbalized1S"),
    "Verbalized2S": (".verbalized_2s", "Verbalized2S"),
    "Linguistic1S": (".linguistic_1s", "Linguistic1S"),
    "RandomBaselineClaim": (".claim.random_baseline", "RandomBaselineClaim"),
    "LabelProb": (".label_prob", "LabelProb"),
    "PTrueEmpirical": (".p_true_empirical", "PTrueEmpirical"),
    "Focus": (".focus", "Focus"),
    "KernelLanguageEntropy": (".kernel_language_entropy", "KernelLanguageEntropy"),
    "LUQ": (".luq", "LUQ"),
    "EigenScore": (".eigenscore", "EigenScore"),
    "CocoaMSP": (".cocoa", "CocoaMSP"),
    "CocoaPPL": (".cocoa", "CocoaPPL"),
    "CocoaMTE": (".cocoa", "CocoaMTE"),
    "RAUQ": (".rauq", "RAUQ"),
    "CSL": (".csl", "CSL"),
    "SemanticDensity": (".semantic_density", "SemanticDensity"),
    "PredictiveKernelEntropy": (
        ".predictive_kernel_entropy",
        "PredictiveKernelEntropy",
    ),
    "SpectralUncertainty": (".spectral_uncertainty", "SpectralUncertainty"),
}

__all__ = list(_EXPORTS)
__getattr__, __dir__ = lazy_exports(__name__, _EXPORTS, globals())
