- name: MaximumSequenceProbability
- name: Perplexity
- name: MeanTokenEntropy
- name: MeanPointwiseMutualInformation
- name: SelfCertainty
- name: MeanConditionalPointwiseMutualInformation
- name: ClaimConditionedProbability
- name: PTrue
- name: PTrueSampling
- name: MonteCarloSequenceEntropy
- name: MonteCarloNormalizedSequenceEntropy
- name: NumSemSets
- name: SemanticEntropy
- name: SAR
- name: TokenSAR
- name: SentenceSAR
- name: LUQ
- name: KernelLanguageEntropy
- name: EigenScore
- name: RenyiNeg
- name: FisherRao
- name: CSL
- name: SemanticDensity
- name: AttentionScore
  cfg:
    gen_only: False
- name: RAUQ
  cfg:
    alpha: 0.2
    use_entropy: False
- name: RAUQ
  cfg:
    alpha: 0.8
    use_entropy: True
- name: LexicalSimilarity
  cfg:
    metric: "rouge1"
- name: LexicalSimilarity
  cfg:
    metric: "rouge2"
- name: LexicalSimilarity
  cfg:
    metric: "rougeL"
- name: LexicalSimilarity
  cfg:
    metric: "BLEU"
- name: EigValLaplacian
  cfg:
    affinity: "entail"
- name: EigValLaplacian
  cfg:
    affinity: "contra"
- name: DegMat
  cfg:
    affinity: "entail"
- name: DegMat
  cfg:
    affinity: "contra"
- name: Eccentricity
  cfg:
    affinity: "entail"
- name: Eccentricity
  cfg:
    affinity: "contra"
- name: EccentricityConf
  cfg:
    affinity: "entail"
- name: EccentricityConf
  cfg:
    affinity: "contra"
- name: EccentricityConfBeamsearch
  cfg:
    affinity: "entail"
    samples_source: beamsearch
- name: EccentricityConfBeamsearch
  cfg:
    affinity: "contra"
    samples_source: beamsearch
- name: CocoaMSP
- name: CocoaMSPBeamsearch
  cfg:
    samples_source: beamsearch
- name: CocoaPPL
- name: CocoaPPLBeamsearch
  cfg:
    samples_source: beamsearch
- name: CocoaMTE
- name: CocoaMTEBeamsearch
  cfg:
    samples_source: beamsearch
- name: Dissimilarity
- name: DissimilarityBeamsearch
  cfg:
    samples_source: beamsearch
