- name: MaximumClaimProbability
- name: PerplexityClaim
- name: MaxTokenEntropyClaim
- name: SelfCertaintyClaim
- name: PointwiseMutualInformationClaim
- name: PTrueClaim
- name: ClaimConditionedProbabilityClaim
  cfg:
    nli_context: "no_context"
- name: ClaimConditionedProbabilityClaim
  cfg:
    nli_context: "fact_pref"
- name: AttentionScoreClaim
  cfg:
    layer: 16
- name: FocusClaim
  cfg:
    model_name: '${model.path}'
    path: "${cache_path}/focus/${model.path}/token_idf.pkl"
    gamma: 0.9
    p: 0.01
    idf_dataset: "togethercomputer/RedPajama-Data-1T-Sample"
    trust_remote_code: True
    idf_seed: 42
    idf_dataset_size: -1
    spacy_path: "en_core_web_sm"
- name: FrequencyScoringClaim
- name: TokenSARClaim