- name: MaximumSequenceProbability
- name: Perplexity
- name: MeanTokenEntropy
- name: TokenSAR
- name: Focus
  cfg:
    model_name: '${model.path}'
    path: "${cache_path}/focus/${model.path}/token_idf.pkl"
    gamma: 0.9
    p: 0.01
    idf_dataset: "ZengXiangyu/RedPajama-Data-1T-Sample"
    trust_remote_code: True
    idf_seed: 42
    idf_dataset_size: -1
    spacy_path: "en_core_web_sm"
