- name: MaximumSequenceProbability
- name: CumulativeMaxSequenceProbability
- name: CumulativePerplexity
- name: CumulativeMeanTokenEntropy
- name: SortedCumulativeMaxSequenceProbability
- name: SortedCumulativePerplexity
- name: SortedCumulativeMeanTokenEntropy
