hydra:
  run:
    dir: ${cache_path}

cache_path: ./workdir/output/calibrated
save_path: '${hydra:run.dir}'

num_bins: 100

manager_paths:
  - /some/absolute/path/to/manager1

generation_metrics:
  - Rouge_rougeL

ue_methods:
  - MaximumSequenceProbability
  - Perplexity
  - MeanTokenEntropy

smoothing:
  do_smooth: true
  bins_per_window: 25
