hydra:
  run:
    dir: ${cache_path}

cache_path: ./workdir/calibrated
save_path: '${hydra:run.dir}'

num_bins: 100

manager_paths:
  - /Users/romanvashurin/workspace/polygraph_calibration/vicuna_aeslc_train_2000.man

generation_metrics:
  - Rouge_rougeL

ue_methods:
  - MaximumSequenceProbability
  - Perplexity
  - MeanTokenEntropy

plot: true

smoothing:
  do_smooth: true
  bins_per_window: 25
