##FROM determinedai/environments:py-3.10-pytorch-2.0-cpu-0.24.0
##RUN apt update && apt install nvidia-cuda-toolkit -y
##RUN pip install torch==2.0.0+cu118 torchvision==0.15.1+cu118 torchaudio==2.0.1 --index-url https://download.pytorch.org/whl/cu118
#FROM mephodybro/det_torch2:0.1
#RUN wget https://raw.githubusercontent.com/IINemo/lm-polygraph/main/scripts/requirements.txt
#RUN pip install -r requirements.txt
#RUN apt install git
#RUN git clone https://github.com/IINemo/lm-polygraph /app
#WORKDIR /app
#RUN pip install .
#RUN rm -rf /root/.cache/*
#RUN apt update && apt install locate -y
