defaults:
  - default

path: google/gemma-3-12b-it
type: vLLMCausalLM
path_to_load_script: model/default_vllm.py
logprobs: 10

load_model_args:
  gpu_memory_utilization: 0.6
  num_gpus: 4

device: cuda
