#!/bin/bash

if command -v python > /dev/null; then
    python -m lm_polygraph.app.service
elif command -v python3 > dev/null; then
    python3 -m lm_polygraph.app.service
else
    echo "No python found, exiting..."
    exit 1
fi
