#!/bin/bash

if command -v python > /dev/null; then
    lib_path=$(python -c 'import pathlib, lm_polygraph; print(pathlib.Path(lm_polygraph.__file__).resolve().parent)')
    cache_path=$lib_path\/app\/cache
    mkdir -p $cache_path

    /usr/bin/env python -m lm_polygraph.app.service --cache-path $cache_path "$@"
elif command -v python3 > /dev/null; then
    lib_path=$(python3 -c 'import pathlib, lm_polygraph; print(pathlib.Path(lm_polygraph.__file__).resolve().parent)')
    cache_path=$lib_path\/app\/cache
    mkdir -p $cache_path

    /usr/bin/env python3 -m lm_polygraph.app.service --cache-path $cache_path "$@"
else
    echo "No python found, exiting..."
    exit 1
fi
