process_output_fn:
  path: instruct/output_processing_scripts/triviaqa.py
  fn_name: normalize_em_triviaqa
process_target_fn:
  path: instruct/output_processing_scripts/triviaqa.py
  fn_name: normalize_em_triviaqa
