stat_calculators:
  - auto
  - name: TrainingStatisticExtractionCalculator
    builder: lm_polygraph.defaults.stat_calculator_builders.default_TrainingStatisticExtractionCalculator
    cfg:
      dataset: '${dataset}'
      text_column: '${text_column}'
      label_column: '${label_column}'
      description: '${description}'
      prompt: '${prompt}'
      few_shot_split: '${few_shot_split}'
      train_split: '${train_split}'
      load_from_disk: '${load_from_disk}'
      subsample_train_dataset: '${subsample_train_dataset}'
      n_shot: '${n_shot}'
      mmlu_max_subject_size: '${mmlu_max_subject_size}'
      train_dataset: '${train_dataset}'
      train_test_split: '${train_test_split}'
      background_train_dataset: '${background_train_dataset}'
      background_train_dataset_text_column: '${background_train_dataset_text_column}'
      background_train_dataset_label_column: '${background_train_dataset_label_column}'
      background_train_dataset_data_files: '${background_train_dataset_data_files}'
      background_load_from_disk: '${background_load_from_disk}'
      subsample_background_train_dataset: '${subsample_background_train_dataset}'
      batch_size: '${batch_size}'
      seed: '${seed}'
    stats: 
      - "train_embeddings"
      - "background_train_embeddings"
      - "train_greedy_log_likelihoods"
    dependencies: