estimators:
  - name: MaximumSequenceProbability
  - name: Perplexity
  - name: MeanTokenEntropy
  - name: MeanPointwiseMutualInformation
  - name: MeanConditionalPointwiseMutualInformation 
  - name: ClaimConditionedProbability
  - name: PTrue
  - name: PTrueSampling
  - name: MonteCarloSequenceEntropy
  - name: MonteCarloNormalizedSequenceEntropy
  - name: LexicalSimilarity
    cfg:
      metric: "rouge1"
  - name: LexicalSimilarity
    cfg:
      metric: "rouge2"
  - name: LexicalSimilarity
    cfg:
      metric: "rougeL"
  - name: LexicalSimilarity
    cfg:
      metric: "BLEU"
  - name: NumSemSets
  - name: EigValLaplacian
    cfg:
      similarity_score: "NLI_score"
      affinity: "entail"
  - name: EigValLaplacian
    cfg:
      similarity_score: "NLI_score"
      affinity: "contra"
  - name: EigValLaplacian
    cfg:
      similarity_score: "Jaccard_score"
  - name: DegMat
    cfg:
      similarity_score: "NLI_score"
      affinity: "entail"
  - name: DegMat
    cfg:
      similarity_score: "NLI_score"
      affinity: "contra"
  - name: DegMat
    cfg:
      similarity_score: "Jaccard_score"
  - name: Eccentricity
    cfg:
      similarity_score: "NLI_score"
      affinity: "entail"
  - name: Eccentricity
    cfg:
      similarity_score: "NLI_score"
      affinity: "contra"
  - name: Eccentricity
    cfg:
      similarity_score: "Jaccard_score"
  - name: SemanticEntropy
  - name: SAR
  - name: TokenSAR
  - name: SentenceSAR
  - name: LUQ
  - name: KernelLanguageEntropy
  - name: EigenScore
  - name: RenyiNeg
  - name: FisherRao
  - name: MahalanobisDistanceSeq
  - name: RelativeMahalanobisDistanceSeq
  - name: RDESeq
  - name: PPLMDSeq
    cfg:
      md_type: "MD"
  - name: PPLMDSeq
    cfg:
      md_type: "RMD"
  - name: Focus
    cfg:
      cache_path: ./workdir/output
      model_name: '${model.path}'
      path: "{cache_path}/{model_name}/token_idf.pkl"
      gamma: 0.9
      p: 0.01
      idf_dataset: "LM-Polygraph/RedPajama-Data-100-Sample-For-Test"
      trust_remote_code: True
      idf_seed: 42
      idf_dataset_size: -1
      spacy_path: "en_core_web_sm"