hydra:
  run:
    dir: ${cache_path}/${task}/${model.path}/${dataset}/${now:%Y-%m-%d}/${now:%H-%M-%S}

defaults:
  - model: bloomz-560m
  - default_estimators
  - default_calculators
  - _self_

cache_path: ./workdir/output
save_path: '${hydra:run.dir}'

device: cpu
instruct: false
task: nmt

dataset: [wmt14, de-en]
text_column: de
label_column: en
description: ""
prompt: "Here is a sentence in {source_lang} language and its translation in {target_lang} language.\n\nOriginal:\n{text}\nTranslation:\n"
n_shot: 0
few_shot_split: train
few_shot_prompt: ""
train_split: train
eval_split: test
max_new_tokens: 107
load_from_disk: false
trust_remote_code: false
generation_params:
  generate_until:
    - "\n"

source_ignore_regex: "(?s).*Original:\n(.*?)\nTranslation:\n"

train_dataset: null
train_test_split: false
test_split_size: 1

background_train_dataset: allenai/c4
background_train_dataset_text_column: text
background_train_dataset_label_column: url
background_train_dataset_data_files: en/c4-train.00000-of-01024.json.gz
background_load_from_disk: false

subsample_background_train_dataset: 1000
subsample_train_dataset: 1000
subsample_eval_dataset: -1

generation_metrics: null

ignore_exceptions: false

batch_size: 1
deberta_batch_size: 10

seed:
    - 1
    
