hydra:
  run:
    dir: ${cache_path}/${task}/${model}/${dataset}/${now:%Y-%m-%d}/${now:%H-%M-%S}

defaults:
  - model: ugrip_llama_instruct
  - dataset: ugrip_gsm8k_direct
  - estimators: ugrip_benchmark_estimators
  - stat_calculators: default_calculators
  - _self_

task: qa
text_column: question
label_column: answer
# Use max_new_tokens= to override
max_new_tokens: 500

cache_path: ./workdir/output
save_path: '${hydra:run.dir}'


train_split: train
eval_split: test
# few_shot_prompt: null
load_from_disk: false
normalize: true
trust_remote_code: false
size: 10000
generation_params:
  generate_until:
    - "\n"

# \/ How many samples per dataset
# Change with +subsample_eval_dataset=25
# subsample_eval_dataset: 25

# \/ What to ignore in model output
# output_ignore_regex: "(?s).### Answer: "
# Below is important for Gemma outputs
output_ignore_regex: "<end_of_turn>"

ignore_exceptions: false

batch_size: 1

seed:
    - 1
