hydra:
  run:
    dir: ${cache_path}/${task}/${model.path}/${dataset}/${now:%Y-%m-%d}/${now:%H-%M-%S}

defaults:
  - model: bloomz-560m
  - default_estimators
  - default_calculators
  - _self_

cache_path: ./workdir/output
save_path: '${hydra:run.dir}'

device: cpu
instruct: false
task: ats

dataset: ['LM-Polygraph/xsum', 'continuation']
text_column: input
label_column: output
train_split: train
eval_split: test
max_new_tokens: 56
load_from_disk: false
trust_remote_code: true
size: 10000
generation_params:
  generate_until:
    - "\n"

subsample_eval_dataset: -1

generation_metrics: null

ignore_exceptions: false

batch_size: 1

seed:
    - 1
