hydra:
  run:
    dir: ${cache_path}/${task}/${model.path}/${dataset}/${now:%Y-%m-%d}/${now:%H-%M-%S}
defaults:
  - model: bloomz-560m
  - _self_

cache_path: ./workdir/output
save_path: '${hydra:run.dir}'
task: test_pooling
dataset: coqa
text_column: questions
label_column: answers
description: "The following are stories and questions about them. Each story is followed by a question and answer to a given question.\n\nStory: {story}"
prompt: "Question: {question}\nAnswer:{answer}"
eval_split: validation
train_split: train
subsample_eval_dataset: 3
max_new_tokens: 30
load_from_disk: false
save_stats:
  - mean_all_layers_embeddings
  - last_all_layers_embeddings
  - best_mean_all_layers_embeddings
  - best_last_all_layers_embeddings

# UE method flags
use_density_based_ue: false
use_seq_ue: false
use_tok_ue: false
use_ens_ue: false
use_claim_ue: false

# Important: Specify generation metrics to avoid loading unnecessary models
generation_metrics: []  # Empty list to disable all metrics for testing

ignore_exceptions: false
batch_size: 2
seed: 
  - 1
