hydra:
  run:
    dir: ${cache_path}/gsm8k_cot/${model}/${dataset}/${now:%Y-%m-%d}/${now:%H-%M-%S}

defaults:
  - model: bloomz-560m
  - _self_

cache_path: ./workdir/output
save_path: '${hydra:run.dir}'

task: qa

base_manager: null
overwrite_base_estimations: false

dataset: [gsm8k, main]
text_column: question
label_column: answer
prompt: "Q: There are 15 trees in the grove. Grove workers will plant trees in the grove today. After they are done, there will be 21 trees. How many trees did the grove workers plant today?\nA: There are 15 trees originally. Then there were 21 trees after some more were planted. So there must have been 21 - 15 = 6. The answer is 6.\n\nQ: If there are 3 cars in the parking lot and 2 more cars arrive, how many cars are in the parking lot?\nA: There are originally 3 cars. 2 more cars arrive. 3 + 2 = 5. The answer is 5.\n\nQ: Leah had 32 chocolates and her sister had 42. If they ate 35, how many pieces do they have left in total?\nA: Originally, Leah had 32 chocolates. Her sister had 42. So in total they had 32 + 42 = 74. After eating 35, they had 74 - 35 = 39. The answer is 39.\n\nQ: Jason had 20 lollipops. He gave Denny some lollipops. Now Jason has 12 lollipops. How many lollipops did Jason give to Denny?\nA: Jason started with 20 lollipops. Then he had 12 after giving some to Denny. So he gave Denny 20 - 12 = 8. The answer is 8.\n\nQ: Shawn has five toys. For Christmas, he got two toys each from his mom and dad. How many toys does he have now?\nA: Shawn started with 5 toys. If he got 2 toys each from his mom and dad, then that is 4 more toys. 5 + 4 = 9. The answer is 9.\n\nQ: There were nine computers in the server room. Five more computers were installed each day, from monday to thursday. How many computers are now in the server room?\nA: There were originally 9 computers. For each of 4 days, 5 more computers were added. So 5 * 4 = 20 computers were added. 9 + 20 is 29. The answer is 29.\n\nQ: Michael had 58 golf balls. On tuesday, he lost 23 golf balls. On wednesday, he lost 2 more. How many golf balls did he have at the end of wednesday?\nA: Michael started with 58 golf balls. After losing 23 on tuesday, he had 58 - 23 = 35. After losing 2 more, he had 35 - 2 = 33 golf balls. The answer is 33.\n\nQ: Olivia has $23. She bought five bagels for $3 each. How much money does she have left?\nA: Olivia had 23 dollars. 5 bagels for 3 dollars each will be 5 x 3 = 15 dollars. So she has 23 - 15 dollars left. 23 - 15 is 8. The answer is 8.\n\nQ: {question}\nA:"
train_split: train
few_shot_split: train
eval_split: test
max_new_tokens: 256
load_from_disk: false
n_shot: 0
normalize: true
generation_params:
  generate_until:
    - "\n"
save_stats:
  - greedy_tokens
  - greedy_log_likelihoods
  - greedy_tokens_alternatives
  - greedy_sentence_similarity
  - token_similarity
  - entropy
  - sample_tokens
  - sample_tokens_alternatives
  - sample_texts
  - sample_log_probs
  - sample_log_likelihoods
  - sample_sentence_similarity
  - sample_token_similarity
  - sample_entropy
  - first_sample_texts
  - best_sample_texts
  - best_sample_text_ids
  - best_normalized_sample_texts
  - best_normalized_sample_text_ids
entropy_top_k: 50

target_ignore_regex: "(?s).*#### "
output_ignore_regex: "(?s).*The answer is "

train_dataset: null
train_test_split: false
test_split_size: 1

background_train_dataset: allenai/c4
background_train_dataset_text_column: text
background_train_dataset_label_column: url
background_train_dataset_data_files: en/c4-train.00000-of-01024.json.gz
background_load_from_disk: false

subsample_background_train_dataset: 1000
subsample_train_dataset: 1000
subsample_eval_dataset: -1

use_density_based_ue: false
use_seq_ue: false
use_tok_ue: false
use_ens_ue: false
generation_metrics: null

additional_estimators:
  - module: lm_polygraph.estimators.monte_carlo_sequence_entropy
    class_name: MonteCarloSequenceEntropy
    kwargs: {}
  - module: lm_polygraph.estimators.monte_carlo_normalized_sequence_entropy
    class_name: MonteCarloNormalizedSequenceEntropy
    kwargs: {}
  - module: lm_polygraph.estimators.semantic_entropy
    class_name: SemanticEntropy
    kwargs: {}

  - module: lm_polygraph.estimators.max_probability
    class_name: MaximumSequenceProbability
    kwargs: {}
  - module: lm_polygraph.estimators.max_probability
    class_name: SampledMaximumSequenceProbability
    kwargs: {}
  - module: lm_polygraph.estimators.sentence_sar
    class_name: SentenceSAR
    kwargs: {}
  - module: lm_polygraph.estimators.gsu
    class_name: MaxprobGSU
    kwargs: {}

  - module: lm_polygraph.estimators.token_sar
    class_name: TokenSAR
    kwargs: {}
  - module: lm_polygraph.estimators.token_sar
    class_name: SampledTokenSAR
    kwargs: {}
  - module: lm_polygraph.estimators.sar
    class_name: SAR
    kwargs: {}
  - module: lm_polygraph.estimators.gsu
    class_name: TokenSARGSU
    kwargs: {}

  - module: lm_polygraph.estimators.perplexity
    class_name: Perplexity
    kwargs: {}
  - module: lm_polygraph.estimators.perplexity
    class_name: SampledPerplexity
    kwargs: {}
  - module: lm_polygraph.estimators.sentence_sar
    class_name: PPLSAR
    kwargs: {}
  - module: lm_polygraph.estimators.gsu
    class_name: PPLGSU
    kwargs: {}

  - module: lm_polygraph.estimators.token_entropy
    class_name: MeanTokenEntropy
    kwargs: {}
  - module: lm_polygraph.estimators.token_entropy
    class_name: SampledMeanTokenEntropy
    kwargs: {}
  - module: lm_polygraph.estimators.sentence_sar
    class_name: MTESAR
    kwargs: {}
  - module: lm_polygraph.estimators.gsu
    class_name: MTEGSU
    kwargs: {}

  - module: lm_polygraph.estimators.average_ue
    class_name: AveMaxprob
    kwargs: {}
  - module: lm_polygraph.estimators.average_ue
    class_name: AvePPL
    kwargs: {}
  - module: lm_polygraph.estimators.average_ue
    class_name: AveTokenSAR
    kwargs: {}
  - module: lm_polygraph.estimators.average_ue
    class_name: AveMTE
    kwargs: {}

  - module: lm_polygraph.estimators.semantic_average_ue_average_similarity
    class_name: SemanticAveMaxprobAveSimilarity
    kwargs: {}

  - module: lm_polygraph.estimators.greedy_semantic_average_ue_average_similarity
    class_name: GreedySemanticAveMaxprobAveSimilarity
    kwargs: {}

ignore_exceptions: false

batch_size: 1
deberta_batch_size: 1

seed:
    - 1
