hydra:
  run:
    dir: ${cache_path}/${task}/${model}/${dataset}/${now:%Y-%m-%d}/${now:%H-%M-%S}

defaults:
  - model: bloomz-560m
  - estimators: default_estimators
  - stat_calculators: default_calculators
  - _self_

cache_path: ./workdir/output
save_path: '${hydra:run.dir}'
instruct: true
task: qa

dataset: ['LM-Polygraph/truthfulqa', 'simple_instruct']
text_column: input
label_column: output
train_split: train
eval_split: test
max_new_tokens: 128
load_from_disk: false
multiref: true
trust_remote_code: false
size: 10000

subsample_eval_dataset: -1

generation_metrics: null

ignore_exceptions: false

batch_size: 2

seed:
    - 1
