hydra:
  run:
    dir: ${cache_path}/${task}/${model.path}/${dataset}/${now:%Y-%m-%d}/${now:%H-%M-%S}

defaults:
  - model: bloomz-560m
  - default_claim_estimators
  - _self_

cache_path: ./workdir/output
save_path: '${hydra:run.dir}'
instruct: false
task: bio

dataset: 'LM-Polygraph/wiki_bio'
text_column: input
eval_split: test
subsample_eval_dataset: 100
max_new_tokens: 256
load_from_disk: false
trust_remote_code: false


use_density_based_ue: false
use_seq_ue: false
use_tok_ue: false
use_ens_ue: false
use_claim_ue: true
generation_metrics: [{
  'name': 'OpenAIFactCheck'
}]
ens_type:

ignore_exceptions: false

batch_size: 1

stat_calculators:
  - auto

seed:
    - 1
