hydra:
  run:
    dir: ${cache_path}/${task}/${dataset}/${now:%Y-%m-%d}/${now:%H-%M-%S}

cache_path: ./workdir/output
save_path: '${hydra:run.dir}'

device: cpu

estimator: null
estimator_module: null
estimator_kwargs: {}

task: ats

dataset: xsum
text_column: document
label_column: summary
prompt: "Summarize the text in a one-sentence headline.\n\nText:\n{text}\n\nSummary (one sentence):\n"
train_split: train
eval_split: test
max_new_tokens: 42
load_from_disk: false

train_dataset: null
train_test_split: false
test_split_size: 1

ood_detection: false
ood_dataset: xsum
ood_text_column: document
ood_label_column: summary
ood_corrupt: true
ood_prompt: null

background_train_dataset: allenai/c4
background_train_dataset_text_column: text
background_train_dataset_label_column: url
background_train_dataset_data_files: en/c4-train.00000-of-01024.json.gz

subsample_background_train_dataset: 10_000
subsample_train_dataset: 10_000
subsample_eval_dataset: -1
subsample_ood_dataset: -1

model: databricks/dolly-v2-3b

use_density_based_ue: true
use_seq_ue: true
use_tok_ue: false

# Examples of providing additional UE methods:
# additional_estimators: {
#   'lm_polygraph.estimators.perplexity': ['Perplexity'],
#   'lm_polygraph.estimators.eig_val_laplacian': ['EigValLaplacian']
# }
# additional_estimators_kwargs: {
#   'Perplexity': {},
#   'EigValLaplacian': {'similarity_score': 'NLI_score', 'affinity': 'entail'}
# }

ignore_exceptions: true

batch_size: 2
deberta_batch_size: 10

seed:
    - 1
