hydra:
  run:
    dir: ${cache_path}/${task}/${model}/${dataset}/${now:%Y-%m-%d}/${now:%H-%M-%S}

defaults:
  - model: kosmos
  - estimators: default_estimators_visual_ex
  - stat_calculators: default_calculators_visual
  - _self_

cache_path: ./workdir/output
save_path: '${hydra:run.dir}'

task: qa

dataset: ['LM-Polygraph/vqa']
text_column: question
label_column: answer
im_column: image
train_split: train
eval_split: test
max_new_tokens: 10
load_from_disk: false
size: 100
generation_params:
  generate_until:
    - "\n"

subsample_eval_dataset: 100

generation_metrics: null

ignore_exceptions: false

batch_size: 1

seed:
    - 1
