hydra:
  run:
    dir: ${cache_path}/${task}/${model.path}/${dataset}/${now:%Y-%m-%d}/${now:%H-%M-%S}

defaults:
  - model: bloomz-560m
  - default_estimators
  - default_calculators
  - _self_

cache_path: ./workdir/output
save_path: '${hydra:run.dir}'

device: cpu
instruct: false
task: ats

dataset: xsum
text_column: document
label_column: summary
description: ""
prompt: "Here's the text and it's short one-sentence summary.\n\nText:\n{text}\n\nSummary (one sentence):\n"
n_shot: 0
few_shot_split: train
few_shot_prompt: ""
train_split: train
eval_split: test
max_new_tokens: 56
load_from_disk: false
trust_remote_code: true
generation_params:
  generate_until:
    - "\n"

subsample_eval_dataset: -1

generation_metrics: null

ignore_exceptions: false

batch_size: 1

seed:
    - 1
